name: Deploy

on:
  push:
    branches:
      - master
          paths:
            - 'data/severe_cases_score_data.csv'
            - 'data/economic_score_data.csv'
            - 'data/mobile_health_score_data.csv'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "test-cvi-dashboard" #Must be unique in Heroku
          heroku_email: "pmmaraujo.public@gmail.com


